# Generated by Django 5.2.5 on 2025-09-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='jersey_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
