# Generated by Django 5.2.5 on 2025-10-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('international', 'International'), ('national', 'National')], max_length=50),
        ),
    ]
